### ISSUE TITLE
Performance issue in some programs

### ISSUE THREAD

**Issue by DLPerf** [captain-pool/GSOC#68]
Hello, I found a Performance issue in in the definition of `call`, E3_Distill_ESRGAN/libs/models/student_rrdb.py, [tf.math.add_n](https://github.com/captain-pool/GSOC/blob/fe215c465becc9e192df06e76511e17a2a7dc082/E3_Distill_ESRGAN/libs/models/student_rrdb.py#L37) will created repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop in train_model_random.

**Comment by captain-pool** [comment]
Hi @DLPerf, thanks for reaching out! I don't have time to fix this. Can you please send a pull request? I can review and merge it.
